default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password123
  host: customer_db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: customer_service_development

test:
  <<: *default
  database: customer_service_test

production:
  <<: *default
  database: customer_service_production
