version: '3.9'

services:
  customer_service_test:
    build: ./monokera_customer_service
    command: ["bash", "-c", "sleep 5 && /wait-for-it.sh rabbitmq:5672 --timeout=30 --strict -- bundle exec rspec"]
    depends_on:
      - customer_db
      - rabbitmq
    volumes:
      - ./monokera_customer_service:/rails
    networks:
      - monokera_net
    environment:
      - RAILS_ENV=test

  order_service_test:
    build: ./monokera_order_service
    command: ["bash", "-c", "sleep 5 && /wait-for-it.sh rabbitmq:5672 --timeout=30 --strict -- bundle exec rspec"]
    depends_on:
      - order_db
      - rabbitmq
    volumes:
      - ./monokera_order_service:/rails
    networks:
      - monokera_net
    environment:
      - RAILS_ENV=test

  customer_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: customer_service_test
    ports:
      - "5543:5432"
    volumes:
      - customer_db_data_test:/var/lib/postgresql/data
    networks:
      - monokera_net

  order_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: order_service_test
    ports:
      - "5544:5432"
    volumes:
      - order_db_data_test:/var/lib/postgresql/data
    networks:
      - monokera_net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - monokera_net

volumes:
  customer_db_data_test:
  order_db_data_test:

networks:
  monokera_net:
    driver: bridge
