services:
  customer_service:
    build: ./monokera_customer_service
    ports:
      - "3001:3000"
    depends_on:
      - customer_db
      - rabbitmq
    volumes:
      - ./monokera_customer_service:/rails
    networks:
      - monokera_net

  order_service:
    build: ./monokera_order_service
    ports:
      - "3002:3000"
    depends_on:
      - order_db
      - rabbitmq
    volumes:
      - ./monokera_order_service:/rails
    networks:
      - monokera_net

  customer_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: customer_service
    ports:
      - "5433:5432"
    volumes:
      - customer_db_data:/var/lib/postgresql/data
    networks:
      - monokera_net

  order_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: order_service
      RABBITMQ_HOST: rabbitmq
    ports:
      - "5434:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - monokera_net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # Dashboard web
      - "5672:5672"    # Puerto de conexión AMQP
    networks:
      - monokera_net

volumes:
  customer_db_data:
  order_db_data:

networks:
  monokera_net:
    driver: bridge
